version: '3.4'
x-restart-policy: &restart_policy
  restart: unless-stopped
x-metamapper-defaults: &metamapper_defaults
  << : *restart_policy
  build:
    context: ./
    args:
      - METAMAPPER_VERSION
  image: 'metamapper-io/metamapper:$METAMAPPER_VERSION'
  env_file:
    - .env
  depends_on:
    - postgres
    - rabbitmq

volumes:
  metamapper-postgres:
    external: true
  metamapper-rabbitmq:
    external: true
