version: '3.4'
x-restart-policy: &restart_policy
  restart: unless-stopped
x-metamapper-defaults: &metamapper_defaults
  << : *restart_policy
  build:
    context: ./
    args:
      - METAMAPPER_IMAGE
      - METAMAPPER_VERSION
  image: metamapper-on-premise
  env_file:
    - .env
  depends_on:
    - postgres
  volumes:
    - ./metamapper/conf:/usr/local/metamapper/metamapper/conf
    - ./metamapper/contrib:/usr/local/metamapper/metamapper/contrib
services:
  postgres:
    << : *restart_policy
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - 'metamapper-postgres:/var/lib/postgresql/data'
  msgbroker:
    << : *restart_policy
    image: redis:alpine
  webserver:
    << : *metamapper_defaults
    command: webserver
    ports:
      - 5050:5050
  worker:
    << : *metamapper_defaults
    command: worker
  scheduler:
    << : *metamapper_defaults
    command: scheduler
volumes:
  metamapper-postgres:
    external: true
  metamapper-msgbroker:
    external: true
