version: 2.1
jobs:
  setup-and-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: ./setup.sh
      - run: docker-compose up -d
      - run:
          name: Ping web service
          command: |
            docker-compose run worker \
              timeout 60 bash \
                -c 'until $(curl -Isf -o /dev/null http://webserver:5050/); do printf '.'; sleep 0.5; done'
      - run: ./healthcheck.sh
workflows:
  pipeline:
    jobs:
      - setup-and-test
